project:
  type: website
  output-dir: docs

website:
  title: "Akshay Prasadan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: industry.qmd
        text: Industry

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    include-in-header:
      text: |
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet"/>

