---
title: "Teaching Experience"
format:
  html:
    toc: true
    toc-depth: 2
    number-sections: false
---

I gained valuable experience as both a teaching assistant and instructor during my PhD.  Teaching assistant responsibilities typically included grading and office hours. Occasionally, I was involved in preparing homeworks/exams with their solutions or proctoring exams. I TAed a total of 11 semesters (listed below), and I was awarded an *Outstanding PhD TA Award* for the 2024-5 academic year. I am the assigned instructor for 36-315 in summer 2025, an undergraduate course on data visualization. I also privately tutored a fellow Statistics PhD student in the fall of 2021.

I consider teaching opportunities very important: they force me to learn material I might otherwise skip over and reveal gaps in my own knowledge I didn't even know existed---the creativity with which students craft questions never ceases to surprise me. Moreover, I built valuable communication skills by working with students whose background ranged from high school to PhD level.

## Teaching Assistant

- **36-225: Introduction to Probability Theory**  
  *Fall 2020*

- **36-401: Modern Regression**  
  *Fall 2022 & Fall 2023* (Head TA in 2023)

- **36-402: Advanced Methods for Data Analysis**  
  *Spring 2025*

- **46-927: Machine Learning II**  
  *Spring 2023 & Spring 2024*

- **46-929: Financial Time Series Analysis**  
  *Spring 2023 & Spring 2024*

- **CMU Summer Undergraduate Research Experience (SURE)**  
  *Summer 2023 & Summer 2024* (Head TA in 2024)

- **36-700: Probability and Mathematical Statistics**  
  *Fall 2024* (Head TA)

## Instructor

- **Statistics & Data Science Camp for High-School Students**  
  *Summer 2023*

- **Guest Lecturer, 36-401: Modern Regression**  
  *Spring 2025*

- **36-315: Statistical Graphics & Visualization**  
  *Summer 2025*
  
